### ISSUE TITLE
undefined method `mime_type' (when removing image)

### ISSUE THREAD

**Issue by jegodwin** [erikdahlstrand/shrine-rails-example#5] opened 2016-01-16 20:45 UTC
I have a User model that `has_one` Profile model, with the Profile model having the image_data attribute. Everything is working fine when uploading the image, but when I check the 'remove attachment' checkbox and submit the form, I get the following error: 
`undefined method 'mime_type' for #<Hash:0x007fed4367c608>`
and references this line in the IMageUploader file: 
`validate_mime_type_inclusion ['image/jpeg', 'image/png', 'image/gif']`

Again, this only happens when removing the image from my Profile model. Any ideas on where I might start looking to troubleshoot this issue?

NOTE: I should also mention that the image does in fact get removed from the model, it just errors on that validation, which seems weird.

**Comment by jegodwin** [comment] 2016-01-16 21:01
After updating my original comment w/ that last 'Note', I think I know what is happening. 

I think that since the model is being updated, it's trying to validate the mime_type, but since the image has been removed, there isn't a file to check the mime_type of.

**Comment by janko-m** [comment] 2016-01-17 04:20
It looks as though Shrine is trying the validate a hash of versions. There is a guard to check if the file exists before validations, so I don't think Shrine tries to validate a missing file.

Since this likely isn't related to the Rails example application, could you open the issue at the Shrine repo, with a script that reproduces the bug (without Rails, you can use the template in CONTRIBUTING.md)?

**Comment by janko-m** [comment] 2016-01-20 09:07
Closing this, the discussion continues here: https://groups.google.com/forum/#!topic/ruby-shrine/YcXJO2cNycI

**Closed by janko-m** 2016-01-20 09:07 UTC
