### ISSUE TITLE
S3 Objects are not deleted

### ISSUE THREAD

**Issue by guzart** [erikdahlstrand/shrine-rails-example#9] opened 2016-02-27 00:23 UTC
After deleting an image the object in S3 (store prefix) is not being deleted.

I thought it could be a permission problem, but I manually deleted the object using the `rails c`.

**Comment by janko-m** [comment] 2016-03-20 15:19
I'm not able to reproduce this. Do you see the images being deleted in the logs? Are you on the latest commit of shrine-rails-example, or are you still on Sidekiq (and not SuckerPunch)? If yes, did you run the app with `foreman start`, so that the Sidekiq process is also ran?

I will close this for now, because I think this is likely a setup issue.

**Closed by janko-m** 2016-03-20 15:19 UTC

**Comment by guzart** [comment] 2016-03-21 16:11
- Latest commit of shrine-rails-example, on master (e4ed7bc)
- Ran bundle install
- Ran bundle exec rake db:setup
- Ran bundle exec rails server

I don't see the image being deleted in the logs

```
Started PATCH "/album.1" for ::1 at 2016-03-21 12:08:34 -0400
Processing by PhotosController#update as
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "album"=>{"photos_attributes"=>{"1"=>{"id"=>"1", "image_data"=>"{\"id\":\"f36....gif\",\"storage\":\"cache\",\"metadata\":{\"size\":22803,\"filename\":\"7d2....gif\",\"mime_type\":\"image/gif\"}}", "_destroy"=>"1"}}}, "commit"=>"Save"}
  Album Load (0.3ms)  SELECT  "albums".* FROM "albums"  ORDER BY "albums"."id" ASC LIMIT 1
   (0.1ms)  begin transaction
  Photo Load (0.3ms)  SELECT "photos".* FROM "photos" WHERE "photos"."album_id" = ? AND "photos"."id" = 1  [["album_id", 1]]
  SQL (0.4ms)  DELETE FROM "photos" WHERE "photos"."id" = ?  [["id", 1]]
   (0.7ms)  commit transaction
Redirected to http://localhost:3030/
Completed 302 Found in 10ms (ActiveRecord: 1.9ms)
```

**Comment by janko-m** [comment] 2016-03-21 16:47
I cannot reproduce it:

```rb
require "./config/environment"
require "stringio"

ImageUploader.opts[:logging_stream] = (stdout = StringIO.new)

image = open("https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png")
photo = Photo.create(image: image)

loop { break if stdout.string.include?("STORE[store]") }

photo.reload.destroy

loop { break if stdout.string.include?("DELETE[destroyed]") }

puts photo.image.values.any?(&:exists?) #=> false
```

**Comment by janko-m** [comment] 2016-03-21 17:39
Can you try to debug why this isn't happening? Maybe you can put a `puts` statement in the `Shrine::Attacher.delete {...}` call in config/initializers/shrine.rb to see if it's even being called. If it is, then you should eventually see the SuckerPunch job being run, maybe SuckerPunch has some logging which notifies in the logs when the job started.

**Comment by guzart** [comment] 2016-03-21 17:41
I'll give it a shot, thanks for the pointers

**Comment by guzart** [comment] 2016-03-21 17:54
Ok, so the problem seems to be when destroying the photo via the album's nested attributes.

**Comment by guzart** [comment] 2016-03-21 17:56
Ok, so the problem seems to be when destroying the photo via the album nested attributes

```
require "./config/environment"

ImageUploader.opts[:logging_stream] = (stdout = StringIO.new)

image = open("https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png")
album = Album.first || Album.create
photo = album.photos.create(image: image)

loop { break if stdout.string.include?("STORE[store]") }

album.update(photos_attributes: { id: photo.id, '_destroy': '1' })

loop { break if stdout.string.include?("DELETE[destroyed]") }

puts photo.image.values.any?(&:exists?) #=> false
```

Maybe destroying via the nested attributes doesn't call the child callbacks? I did a quick search to see if this was the case, but I couldn't find anything.

**Comment by janko-m** [comment] 2016-03-22 00:01
Ok, managed to get to the bottom on it, and fixed it. This was only happening when the page wasn't refreshed since the image got promoted, so the view was still showing the cached version. Because for some reason I have the `image_data` field being sent along other parameters, ActiveRecord instantiates the photo object with the given attributes (so the cached attachment, even though the it was already promoted), and then the deleting would abort because it sees only the cached attachment.

I fixed this by not sending the `image_data` field. Thanks letting me know and being persistent!

**Comment by guzart** [comment] 2016-03-22 03:05
Fix confirmed.
You are welcome, and thank you for all your excellent work and open sourcing shrine.
